name: Test server

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: 16 
        cache: 'npm'
        working-directory: ./server
    - run: npm ci
        working-directory: ./server
    - run: npm run build
        working-directory: ./server
    - run: npm run test
        working-directory: ./server
