name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      working-directory: ./server
    - run: npm run build
      working-directory: ./server
    - run: npm run lint
      working-directory: ./server
    - run: npm run test
      working-directory: ./server
    - run: npm ci
      working-directory: ./client
    - run: npm run build
      working-directory: ./client
    - run: npm ci
      working-directory: ./e2e
